# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.destroy_all

demo = User.create!(username: 'demo', password: 'password')

jomez = User.create!(username: 'JomezPro', password: 'discgolf')
superman = User.create!(username: 'Superman', password: 'loislane')
animalkingdom = User.create!(username: 'AnimalKingdom', password: 'skatpoop')
homevideos = User.create!(username: 'HomeVideos', password: 'americasfuniest')
movies = User.create!(username: 'movies', password: 'password')




user1 = User.create!(username: 'user1', password: 'starwars')
user2 = User.create!(username: 'user2', password: 'starwars')
user3 = User.create!(username: 'user3', password: 'starwars')
user4 = User.create!(username: 'user4', password: 'starwars')
user5 = User.create!(username: 'user5', password: 'starwars')
user6 = User.create!(username: 'user6', password: 'starwars')
user7 = User.create!(username: 'user7', password: 'starwars')
user8 = User.create!(username: 'user8', password: 'starwars')
user9 = User.create!(username: 'user9', password: 'starwars')
user10 = User.create!(username: 'user10', password: 'starwars')
user11 = User.create!(username: 'user11', password: 'starwars')
user12 = User.create!(username: 'user12', password: 'starwars')
user13 = User.create!(username: 'user13', password: 'starwars')
user14 = User.create!(username: 'user14', password: 'starwars')
user15 = User.create!(username: 'user15', password: 'starwars')
user16 = User.create!(username: 'user16', password: 'starwars')
user17 = User.create!(username: 'user17', password: 'starwars')
user18 = User.create!(username: 'user18', password: 'starwars')
user19 = User.create!(username: 'user19', password: 'starwars')
user20 = User.create!(username: 'user20', password: 'starwars')
user21 = User.create!(username: 'user21', password: 'starwars')
user22 = User.create!(username: 'user22', password: 'starwars')
user23 = User.create!(username: 'user23', password: 'starwars')
user24 = User.create!(username: 'user24', password: 'starwars')
user25 = User.create!(username: 'user25', password: 'starwars')
user26 = User.create!(username: 'user26', password: 'starwars')
user27 = User.create!(username: 'user27', password: 'starwars')
user28 = User.create!(username: 'user28', password: 'starwars')
user29 = User.create!(username: 'user29', password: 'starwars')
user30 = User.create!(username: 'user30', password: 'starwars')
user31 = User.create!(username: 'user31', password: 'starwars')
user32 = User.create!(username: 'user32', password: 'starwars')
user33 = User.create!(username: 'user33', password: 'starwars')
user34 = User.create!(username: 'user34', password: 'starwars')
user35 = User.create!(username: 'user35', password: 'starwars')
user36 = User.create!(username: 'user36', password: 'starwars')
user37 = User.create!(username: 'user37', password: 'starwars')
user38 = User.create!(username: 'user38', password: 'starwars')
user39 = User.create!(username: 'user39', password: 'starwars')
user40 = User.create!(username: 'user40', password: 'starwars')
user41 = User.create!(username: 'user41', password: 'starwars')
user42 = User.create!(username: 'user42', password: 'starwars')
user43 = User.create!(username: 'user43', password: 'starwars')
user44 = User.create!(username: 'user44', password: 'starwars')
user45 = User.create!(username: 'user45', password: 'starwars')
user46 = User.create!(username: 'user46', password: 'starwars')
user47 = User.create!(username: 'user47', password: 'starwars')
user48 = User.create!(username: 'user48', password: 'starwars')
user49 = User.create!(username: 'user49', password: 'starwars')
user50 = User.create!(username: 'user50', password: 'starwars')
user51 = User.create!(username: 'user51', password: 'starwars')
user52 = User.create!(username: 'user52', password: 'starwars')
user53 = User.create!(username: 'user53', password: 'starwars')
user54 = User.create!(username: 'user54', password: 'starwars')
user55 = User.create!(username: 'user55', password: 'starwars')
user56 = User.create!(username: 'user56', password: 'starwars')
user57 = User.create!(username: 'user57', password: 'starwars')
user58 = User.create!(username: 'user58', password: 'starwars')
user59 = User.create!(username: 'user59', password: 'starwars')
user60 = User.create!(username: 'user60', password: 'starwars')
user61 = User.create!(username: 'user61', password: 'starwars')
user62 = User.create!(username: 'user62', password: 'starwars')
user63 = User.create!(username: 'user63', password: 'starwars')
user64 = User.create!(username: 'user64', password: 'starwars')
user65 = User.create!(username: 'user65', password: 'starwars')
user66 = User.create!(username: 'user66', password: 'starwars')
user67 = User.create!(username: 'user67', password: 'starwars')
user68 = User.create!(username: 'user68', password: 'starwars')
user69 = User.create!(username: 'user69', password: 'starwars')
user70 = User.create!(username: 'user70', password: 'starwars')
user71 = User.create!(username: 'user71', password: 'starwars')
user72 = User.create!(username: 'user72', password: 'starwars')
user73 = User.create!(username: 'user73', password: 'starwars')
user74 = User.create!(username: 'user74', password: 'starwars')
user75 = User.create!(username: 'user75', password: 'starwars')
user76 = User.create!(username: 'user76', password: 'starwars')
user77 = User.create!(username: 'user77', password: 'starwars')
user78 = User.create!(username: 'user78', password: 'starwars')
user79 = User.create!(username: 'user79', password: 'starwars')
user80 = User.create!(username: 'user80', password: 'starwars')
user81 = User.create!(username: 'user81', password: 'starwars')
user82 = User.create!(username: 'user82', password: 'starwars')
user83 = User.create!(username: 'user83', password: 'starwars')
user84 = User.create!(username: 'user84', password: 'starwars')
user85 = User.create!(username: 'user85', password: 'starwars')
user86 = User.create!(username: 'user86', password: 'starwars')
user87 = User.create!(username: 'user87', password: 'starwars')
user88 = User.create!(username: 'user88', password: 'starwars')
user89 = User.create!(username: 'user89', password: 'starwars')
user90 = User.create!(username: 'user90', password: 'starwars')
user91 = User.create!(username: 'user91', password: 'starwars')
user92 = User.create!(username: 'user92', password: 'starwars')
user93 = User.create!(username: 'user93', password: 'starwars')
user94 = User.create!(username: 'user94', password: 'starwars')
user95 = User.create!(username: 'user95', password: 'starwars')
user96 = User.create!(username: 'user96', password: 'starwars')
user97 = User.create!(username: 'user97', password: 'starwars')
user98 = User.create!(username: 'user98', password: 'starwars')
user99 = User.create!(username: 'user99', password: 'starwars')
user100 = User.create!(username: 'user100', password: 'starwars')











Video.destroy_all

# video = Video.create!(title: , description: , author_id: , video: )

video1 = Video.create!(title: "Sortalot app demo", description: "This game isn't complete yet, this is just a demo version", video: 'https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Sortalot.mov', author_id: homevideos.id)

video2 = Video.create!(title: 'Paul McBeth Disc Golf Hole In One - Texas States 2017 Round Two
', description: "Paul McBeth Disc Golf Hole In One Ace\r\nTexas States Disc Golf Championship 2017 Round Two\r\nHole 15 Milby Disc Golf Course Houston, Texas\r\nJomez Productions\r\n\rCamera: Chase Hayden\r\n\rGraphics by Overstable Studios",
video: 'https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Paul+McBeth+Disc+Golf+Hole+In+One+-+Texas+States+2017+Round+Two.mp4', author_id: jomez.id, view_count: 64014)

video3 = Video.create!(title: "Now THIS is as close to an ACE as you can get! | Paul McBeth", description: "Paul McBeth nearly aces Hole 5 at the Eureka Temp course in Round 3 of the 2017 Ledgestone Insurance Open.\r\n\rGraphics by Overstable Studios\r\n\rMusic by Starframe Audio", video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Now+THIS+is+as+close+to+an+ACE+as+you+can+get!+-+Paul+McBeth.mp4", author_id: jomez.id, view_count: 82492)

video5 = Video.create!(title: "Some llamas are in town", description: "All the animals are just hanging around\r\n\rWould you like to join them?\r\nWell come on down to farmer bob's farms and we will seat ya and have ya a real good dinner!", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/SeveralAnimals.mp4" )

video6 = Video.create!(title: "Sneak on the squirrel in the rubbish", description: "Well this little guy never knew what was coming did he!!!! LOLOL", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20170422_191430.mp4")

video7 = Video.create!(title: "My little cousin throwing a disc golf disc", description: "He pretty gud aye", author_id: homevideos.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20170622_123039.mp4")

video8 = Video.create!(title: "Stare off with some cows", description: "Bondurant, WY (outside of Jackson Hole)", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20170626_205230.mp4")

video9 = Video.create!(title: "Little ferret too tired to move", description: "ain't she adorable", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20170703_000056.mp4")

video10 = Video.create!(title: "Little ferret digging in the rice bucket", description: "Don't worry, it's exercise rice", author_id: animalkingdom.id , video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20170724_220516.mp4")

video11 = Video.create!(title: "Little ferret roams the wilds of the grass", description: "Don't worry little ferret, you'll always make your way back home", author_id: animalkingdom.id , video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20171007_171131.mp4")

video12 = Video.create!(title: "Little ferret digging in the rocks", description: "Little ferret found a nice spot", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20171007_171540.mp4")

video13 = Video.create!(title: "Little ferret trying to make a hole", description: "Little ferret at it again I guess...Always with the digger", author_id: animalkingdom.id , video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20171007_171712.mp4")

video14 = Video.create!(title: "2017 Memorial Championship | Final Round, Pt1 | Wysocki, McBeth, Lizotte, Sexton
" , description: "Jomez Productions in association with Disc Golf Pro Tour, Discraft, and Overstable Studios presents coverage of the 2017 Memorial Championship MPO.\r\n\rCommentary by Nate Sexton and Paul McBeth\r\n\rFeaturing:\r\nRicky Wysocki\r\nPaul McBeth\r\nSimon Lizotte\r\nNate Sexton", author_id: jomez.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/2017+Memorial+Championship+-+Final+Round%2C+Pt1+-+Wysocki%2C+McBeth%2C+Lizotte%2C+Sexton.mp4", view_count: 199797)


video15 = Video.create!(title: "2017 PDGA Pro Worlds | Final Round, Front 9 | Wysocki, Lizotte, McCray, Hammes", description: "Jomez Productions in association with Innova Champion Discs, the Professional Disc Golf Association, and Overstable Studios presents Final Round MPO Lead Card coverage of the 2017 PDGA Professional Disc Golf World Championships.\r\n\rCommentary by Jeremy Koling and Steve Hill\r\n\rFeaturing:\r\nRicky Wysocki\r\nSimon Lizotte\r\nJohnE McCray\r\nAdam Hammes", author_id: jomez.id, view_count: 110668, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/2017+PDGA+Pro+Worlds+-+Final+Round%2C+Front+9+-+Wysocki%2C+Lizotte%2C+McCray%2C+Hammes.mp4")

video16 = Video.create!(title: "2017 PDGA Pro Worlds | Final 9 | Wysocki, Lizotte, McCray, Hammes", description: "Jomez Productions in association with Innova Champion Discs, the Professional Disc Golf Association, and Overstable Studios presents Final Round MPO Lead Card coverage of the 2017 PDGA Professional Disc Golf World Championships.\r\n\rCommentary by Jeremy Koling and Steve Hill\r\n\rFeaturing:\r\nRicky Wysocki\r\nSimon Lizotte\r\nJohnE McCray\r\nAdam Hammes", author_id: jomez.id, view_count: 110514, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/2017+PDGA+Pro+Worlds+-+Final+9+-+Wysocki%2C+Lizotte%2C+McCray%2C+Hammes.mp4")

video17 = Video.create!(title: "Little ferret big rocks", description: "Little ferret goes to town on the big rocks\r\n\rThis is the next installment in the Little ferret series\r\n\rIf you'd like to see more then please subscribe!!", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20171007_173202.mp4")

video18 = Video.create!(title: "Little ferret big NatGeo?", description: "Little ferret performs an exhilierating search of the forest.\r\n\r", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/20171007_173801.mp4")


video19 = Video.create!(title: "ACE! Philo Brathwaite #SCTOP10", description: "Philo Brathwaite hits an ACE that landed him on SportsCenter Top10 at #8! Hole 12 (177ft) at R.L. Smith in Charlotte, NC at the 4th Annual 21 Hole Salute Presented By Dynamic Discs. Coverage also made possible by Final Round Radio.\r\n\rFor permission to use this video please contact us at: jomezprod(at)gmail.com", author_id: jomez.id, view_count: 39884, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/ACE!+Philo+Brathwaite+%23SCTOP10.mp4")

video20 = Video.create!(title: "Basket Dash - Series Premiere | Ep1 | Discmania / Innova / Dynamic", description: "We are proud to present the series premiere of the Jomez Pro Basket Dash in association with BlackInkDiscs.com!\r\n\rWe’ve brought together your favorite Disc Golf Pros to test their skills in a unique way never seen before. \r\n\rTeam Dynamic:\r\nEric Oakley\r\nDrew Gibson\r\nPaige Pierce\r\n\rTeam Discmania:\r\nSimon Lizotte\r\nNate Perkins\r\nEagle McMahon\r\n\rTeam Innova:\r\nPaul McBeth\r\nNate Sexton\r\nJeremy Koling\r\n\rOur first episode brings us to Moraine State Park in Pittsburgh, Pennsylvania. Home of the Pittsburgh Flying Disc Open and the 2015 PDGA Pro World Championships. \r\n\rStay Tuned for our next episode, coming soon, from Smuggs DGC in Smuggler’s Notch, Vermont. Home of the Green Mountain Championship!", author_id: jomez.id, view_count: 39067, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Basket+Dash+-+Series+Premiere+-+Ep1+-+Discmania+-+Innova+-+Dynamic.mp4")

video21 = Video.create!(title: "Eagle vs Simon Trick Shot | Top of the Tower Disc Golf", description: "Eagle McMahon and Simon Lizotte battle to see who can hit the top of the water tower at Lake Eureka after the 2015 Ledgestone Open. After many unsuccessful attempts they end up both hitting it back to back!", author_id: jomez.id , view_count: 18960, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Eagle+vs+Simon+Trick+Shot+-+Top+of+the+Tower+Disc+Golf.mp4")

# video = Video.create!(title: , description: , author_id: , view_count: , video: )

video22 = Video.create!(title: "GBO 2015 Final Round | McBeth,McMahon,Schusterick,Feldberg", description: "Full Coverage of the Final Round MPO Lead Card at the 2015 Glass Blown Open by Dynamic Discs in Emporia, Kansas. Played at the Emporia Country Club Course. Featuring Paul McBeth, Eagle McMahon, Will Schusterick, and David Feldberg. 2015 Jomez Productions Disc Golf", author_id: jomez.id, view_count: 277869, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/GBO+2015+Final+Round+-+McBeth%2CMcMahon%2CSchusterick%2CFeldberg.mp4" )


video23 = Video.create!(title: "GBO 2016 Final Round | McBeth,Todd,Wysocki,Wegryn", description: "Jomez Productions presents MPO coverage of the 2016 Glass Blown Open. This final round lead card includes Paul McBeth, Cameron Todd, Ricky Wysocki, and Nate Wegryn. Played at Emporia Country Club in Emporia, Kansas. Commentary provided by Jomez & Ian of Central Coast Disc Golf. Jomez Productions Disc Golf 2016", author_id: jomez.id, view_count: 205586, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/GBO+2016+Final+Round+-+McBeth%2CTodd%2CWysocki%2CWegryn.mp4")

video24 = Video.create!(title: "Check out this wild looking duck!", description: "We have all of the greatest in crazy animals.\r\nWe upload at least once at some time or another.", author_id: animalkingdom.id, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Multicolor_Duck.mpeg")

video25 = Video.create!(title: "Never Been Hit: Catch Cam Chronicles", description: "The life of a Disc Golf coverage catch cam operator isn't easy. One must always been in the line of fire in order to catch the perfect angle as the world's top professionals hurl chunks of plastic toward the chains in their quest for birdies.\r\n\r\nOver the past few years, Michael has had some VERY close calls, but to this day has NEVER been hit! He has an incredible sixth sense about him that allows him to avoid contact with the discs while maintaining his composure and getting some great shots.\r\n\r\nThis is a small glimpse into the life of a catch cam operator.\r\n\r\nJomez Productions Disc Golf 2017\r\n\r\nPlastic Hurlers:\r\nPaul McBeth\r\nRicky Wysocki\r\nNate Sexton\r\nSimon Lizotte\r\nEagle McMahon\r\nJeremy Koling\r\nJohne McCray\r\nWill Schusterick\r\nPhilo Brathwaite\r\nNikko Locastro" , author_id: jomez.id, view_count: 25616, video: "https://s3.amazonaws.com/blutube-dev/videos/videos/000/000/Never+Been+Hit-+Catch+Cam+Chronicles.mp4")




Like.destroy_all

Like.create!(user_id: user1.id, video_id: video1.id, like_value: true)
Like.create!(user_id: user2.id, video_id: video1.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video1.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video1.id, like_value: true)
Like.create!(user_id: user5.id, video_id: video1.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video1.id, like_value: false)

Like.create!(user_id: user1.id, video_id: video2.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video2.id, like_value: false)
Like.create!(user_id: user3.id, video_id: video2.id, like_value: false)
Like.create!(user_id: user4.id, video_id: video2.id, like_value: false)
Like.create!(user_id: user5.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user6.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user7.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user8.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user9.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user10.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video2.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video2.id, like_value: true)


Like.create!(user_id: user1.id, video_id: video3.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video3.id, like_value: false)
Like.create!(user_id: user3.id, video_id: video3.id, like_value: false)
Like.create!(user_id: user4.id, video_id: video3.id, like_value: false)
Like.create!(user_id: user5.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user6.id, video_id: video3.id, like_value: false)
Like.create!(user_id: user7.id, video_id: video3.id, like_value: false)
Like.create!(user_id: user8.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user9.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user10.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user14.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user15.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user16.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video3.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video3.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user3.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user4.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user5.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user7.id, video_id: video5.id, like_value: false)
Like.create!(user_id: user8.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user9.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user10.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user14.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user15.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user16.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video5.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video5.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user3.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user4.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user5.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user7.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user8.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user9.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user10.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user14.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user15.id, video_id: video6.id, like_value: false)
Like.create!(user_id: user16.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video6.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video6.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user5.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user7.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user8.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user9.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user10.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user14.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user15.id, video_id: video7.id, like_value: false)
Like.create!(user_id: user16.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video7.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video7.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user5.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user7.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user8.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user9.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user10.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user14.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user15.id, video_id: video8.id, like_value: false)
Like.create!(user_id: user16.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video8.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video8.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video9.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user5.id, video_id: video9.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user7.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user8.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user9.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user10.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user11.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user12.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video9.id, like_value: false)
Like.create!(user_id: user14.id, video_id: video9.id, like_value: false)
Like.create!(user_id: user15.id, video_id: video9.id, like_value: false)
Like.create!(user_id: user16.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video9.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video9.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user2.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user3.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user4.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user5.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video10.id, like_value: true)
Like.create!(user_id: user7.id, video_id: video10.id, like_value: true)
Like.create!(user_id: user13.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user14.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user15.id, video_id: video10.id, like_value: false)
Like.create!(user_id: user16.id, video_id: video10.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video10.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video10.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user2.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video11.id, like_value: false)
Like.create!(user_id: user5.id, video_id: video11.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user7.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user16.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video11.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video11.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user2.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user5.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user7.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user16.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user18.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user19.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user20.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user21.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user22.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user23.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user24.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user25.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user26.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user27.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user28.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user29.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user30.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user31.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user32.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user33.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user34.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user35.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user36.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user37.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user38.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user39.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user40.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user41.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user42.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user43.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user44.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user45.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user46.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user47.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user48.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user49.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user50.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user51.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user52.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user53.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user54.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user55.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user56.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user57.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user58.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user59.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user60.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user61.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user62.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user63.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user64.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user65.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user66.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user67.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user68.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user69.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user70.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user71.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user72.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user73.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user74.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user75.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user76.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user77.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user78.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user79.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user80.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user81.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user82.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user83.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user84.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user85.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user86.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user87.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user88.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user89.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user90.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user91.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user92.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user93.id, video_id: video12.id, like_value: false)
Like.create!(user_id: user94.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user95.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user96.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user97.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user98.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user99.id, video_id: video12.id, like_value: true)
Like.create!(user_id: user100.id, video_id: video12.id, like_value: true)

Like.create!(user_id: user1.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user2.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user3.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user4.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user5.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user6.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user7.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user16.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user17.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user18.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user19.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user20.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user21.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user22.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user23.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user24.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user25.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user26.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user27.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user28.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user29.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user30.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user31.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user32.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user33.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user34.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user35.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user36.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user37.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user38.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user39.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user40.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user41.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user42.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user43.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user44.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user45.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user46.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user47.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user48.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user49.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user50.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user51.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user52.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user53.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user54.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user55.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user56.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user57.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user58.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user59.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user60.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user61.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user62.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user63.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user64.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user65.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user66.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user67.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user68.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user69.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user70.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user71.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user72.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user73.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user74.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user75.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user76.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user77.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user78.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user79.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user80.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user81.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user82.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user83.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user84.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user85.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user86.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user87.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user88.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user89.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user90.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user91.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user92.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user93.id, video_id: video13.id, like_value: false)
Like.create!(user_id: user94.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user95.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user96.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user97.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user98.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user99.id, video_id: video13.id, like_value: true)
Like.create!(user_id: user100.id, video_id: video13.id, like_value: true)
